name = "ImaginaryOptics"
uuid = "ed0a9f63-0a1c-4465-a5fd-c9e4b6c1d448"
authors = ["Marco Menarini <menarini.marco@gmail.com>"]
version = "1.0.0-DEV"

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
